invoicemanager/invoicemanager/urls.py
from django.urls import path

from . import views

app_name = "invoicemanager"
urlpatterns = [

	# # # DEFAULT

	path('', views.invoices.index, name='index'),

    # # # INVOICES

    path('invoice/new/', views.invoices.new_invoice, name='new_invoice'),
    path('invoice/all/', views.invoices.all_invoices, name='all_invoices'),
    path('invoice/draft/', views.invoices.draft_invoices, name='draft_invoices'),
    path('invoice/paid/', views.invoices.paid_invoices, name='paid_invoices'),
    path('invoice/unpaid/', views.invoices.unpaid_invoices, name='unpaid_invoices'),
    path('invoice/<int:invoice_id>/', views.invoices.invoice, name='invoice'),
    path('invoice/search/', views.invoices.search_invoice, name='search_invoice'),
    path('invoice/<int:invoice_id>/update/', views.invoices.update_invoice, name='update_invoice'),
    path('invoice/<int:invoice_id>/print/', views.invoices.print_invoice, name='print_invoice'),
    path('invoice/<int:invoice_id>/delete/', views.invoices.delete_invoice, name='delete_invoice'),

    # # # ITEMS

    path('invoice/<int:invoice_id>/item/add/', views.items.add_item, name='add_item'),
    path('invoice/<int:invoice_id>/item/<int:invoiceitem_id>/delete/', views.items.delete_item, name='delete_item'),

    # # # INVOICE EXPENSES

    path('invoice/<int:invoice_id>/expenses/add/', views.expenses.add_invoice_expense, name='add_invoice_expense'),
    path('invoice/<int:invoice_id>/expenses/<int:expense_id>/delete/', views.expenses.delete_invoice_expense, name='delete_invoice_expense'),

    # # # BUSINESS EXPENSES

    path('expenses/', views.expenses.expense_list, name='expense_list'),
    path('expenses/new/', views.expenses.new_business_expense, name='new_business_expense'),
    path('expenses/<int:expense_id>/delete/', views.expenses.delete_business_expense, name='delete_business_expense'),

    # # # REPORTS

    path('accounting/', views.reports.accounting, name='accounting'),

    # # # ATTACHMENTS

    path('invoice/<int:invoice_id>/attachments/add/', views.invoices.upload_invoice_attachment, name='upload_invoice_attachment'),
    path('invoice/<int:invoice_id>/attachments/<int:invoiceattachment_id>/delete/', views.invoices.delete_invoice_attachment, name='delete_invoice_attachment'),
    path('expenses/<int:invoice_id>/attachments/add/', views.expenses.upload_business_expense_attachment, name='upload_business_expense_attachment'),

    # # # CUSTOMERS

    path('customers/', views.customers.customer_list, name='customer_list'),
    path('customer/<int:customer_id>/', views.customers.customer, name='customer'),
	path('customer/<int:customer_id>/update/', views.customers.update_customer, name='update_customer'),
    path('customer/<int:customer_id>/delete/', views.customers.delete_customer, name='delete_customer'),
    path('customer/new/', views.customers.new_customer, name='new_customer'),

    # # # USER AUTHENTICATION

    path('login/', views.userauth.login_view, name='login'),
    path('logout/', views.userauth.logout_view, name='logout'),

    # # # ADMIN

    path('users/', views.admin.users, name='users'),
    path('settings/', views.admin.settings, name='settings'),
]

invoicemanager/invoicemanager/models.py
from __future__ import unicode_literals

from django.core.files.storage import FileSystemStorage
from django.db import models

# Create your models here.
class Customer(models.Model):
	name = models.CharField(max_length=256)
	address1 = models.CharField(max_length=256, blank=True)
	address2 = models.CharField(max_length=256, blank=True)
	city = models.CharField(max_length=128, blank=True)
	state = models.CharField(max_length=2, blank=True)
	zip = models.CharField(max_length=12, blank=True)
	email = models.CharField(max_length=256, blank=True)

	def __str__(self):
		return self.name
	
	def invoices(self):
		return Invoice.objects.filter(customer=self).count()

class Invoice(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
	date = models.DateField()
	status = models.CharField(max_length=10)

	def __str__(self):
	    return str(self.id)

	def total_items(self):
		total = 0
		items = self.invoiceitem_set.all()

		for item in items:
			total += item.cost * item.qty

		return total

	def total_expenses(self):
		total = 0
		expenses = self.expense_set.all()

		for expense in expenses:
			total += expense.cost * expense.qty

		return total

	def total(self):
		items = self.total_items()
		expenses = self.total_expenses()

		return items - expenses
		
	def paid(self):
		return self.status == 'Paid'
		
	def unpaid(self):
		return self.status == 'Unpaid'
		
	def draft(self):
		return self.status == 'Draft'

class InvoiceItem(models.Model):
	invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
	name = models.CharField(max_length=128)
	description = models.TextField()
	cost = models.DecimalField(decimal_places=2, max_digits=10)
	qty = models.IntegerField()

	def total(self):
		return self.cost * self.qty

class Expense(models.Model):
	description = models.TextField()
	cost = models.DecimalField(decimal_places=2, max_digits=10)
	qty = models.IntegerField()
	invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, blank=True, null=True)
	date = models.DateField(blank=True, null=True)
		
	def total(self):
		return self.cost * self.qty

	def is_business_expense(self):
		return self.invoice is None

class InvoiceAttachment(models.Model):
	file = models.FileField(upload_to='invoice/')
	displayname = models.CharField(max_length=128)
	invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)

class ExpenseAttachment(models.Model):
	file = models.FileField(upload_to='expense/')
	displayname = models.CharField(max_length=128)
	expense = models.ForeignKey(Expense, on_delete=models.CASCADE)

invoicemanager/invoicemanager/views/admin.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
import datetime

from invoicemanager.models import Customer, Invoice, InvoiceItem, Expense, InvoiceAttachment, ExpenseAttachment	



# Administrative settings
def users(request):
    return None


def settings(request):
    return None

invoicemanager/invoicemanager/views/customers.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import datetime

from invoicemanager.models import Customer, Invoice, InvoiceItem, Expense, InvoiceAttachment, ExpenseAttachment



# List all customers
@login_required(login_url='login/')
def customer_list(request):
	customers = Customer.objects.all()
	context = {
		'title' : 'Customer List',
		'customers' : customers,
	}
	return render(request, 'customers.html', context)



# Show specific customer details
@login_required(login_url='login/')
def customer(request, customer_id):
	customer = get_object_or_404(Customer, pk=customer_id)
	invoices = Invoice.objects.filter(customer = customer)
	context = {
		'title' : "Customer info - %s" % customer.name,
		'customer' : customer,
		'invoices' : invoices,
	}
	return render(request, 'customer.html', context)



# Add new customer
@login_required(login_url='login/')
def new_customer(request):
	if request.method == 'POST':
		# Stuff from form
		c = Customer(name=request.POST['name'], address1=request.POST['address1'], address2=request.POST['address2'], city=request.POST['city'], state=request.POST['state'], zip=request.POST['zip'], email=request.POST['email'])
		c.save()

		if 'savecreate' in request.POST:
			i = Invoice(customer=c, date=datetime.date.today(), status='Unpaid')
			i.save()
			return HttpResponseRedirect(reverse('invoice', args=(i.id,)))
		else:
			return HttpResponseRedirect(reverse('customer_list'))
	else:
		return render(request, 'new_customer.html')



# Update customer
@login_required(login_url='login/')
def update_customer(request, customer_id):
	# Stuff from form
	c = get_object_or_404(Customer, pk=customer_id)

	c.name = request.POST['name']
	c.address1 = request.POST['address1']
	c.address2 = request.POST['address2']
	c.city = request.POST['city']
	c.state = request.POST['state']
	c.zip = request.POST['zip']
	c.email = request.POST['email']

	c.save()

	return HttpResponseRedirect(reverse('customer', args=(c.id,)))


# Delete customer
@login_required(login_url='login/')
def delete_customer(request, customer_id):
	customer = get_object_or_404(Customer, pk=customer_id)
	customer.delete()
	return HttpResponseRedirect(reverse('customer_list'))

invoicemanager/invoicemanager/views/expenses.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
import datetime

from invoicemanager.models import Customer, Invoice, InvoiceItem, Expense, InvoiceAttachment, ExpenseAttachment



# Add expense to invoice
@login_required(login_url='login/')
def add_invoice_expense(request, invoice_id):
	invoice = get_object_or_404(Invoice, pk=invoice_id)
	try:
		e = invoice.expense_set.create(description=request.POST['description'], cost=request.POST['cost'], qty=request.POST['qty'])
		e.save()
	except (KeyError, Invoice.DoesNotExist):
		return render(request, 'view_invoice.html', {
			'invoice': invoice,
			'error_message': 'Not all fields were completed.',
		})
	else:
		return HttpResponseRedirect(reverse('invoice', args=(invoice.id,)))



# Delete expense from invoice
@login_required(login_url='login/')
def delete_invoice_expense(request, expense_id, invoice_id):
	expense = get_object_or_404(Expense, pk=expense_id)
	invoice = get_object_or_404(Invoice, pk=invoice_id)
	try:
		expense.delete()
	except (KeyError, Expense.DoesNotExist):
		return render(request, 'view_invoice.html', {
			'invoice': invoice,
			'error_message': 'Expense does not exist.',
		})
	else:
		return HttpResponseRedirect(reverse('invoice', args=(invoice.id,)))



# List all business expenses (expense item with no invoice_id)
@login_required(login_url='login/')
def expense_list(request):
	expenses = Expense.objects.filter(invoice_id=None)
	context = {
		'expenses' : expenses,
	}
	return render(request, 'expenses.html', context)



# New business expense
@login_required(login_url='login/')
def new_business_expense(request):
	if request.method == 'POST':
		# Stuff from form
		date = datetime.datetime.strptime(request.POST['date'], "%m/%d/%Y")
		e = Expense(description=request.POST['description'], date=date, cost=request.POST['cost'], qty=request.POST['qty'])
		e.save()
		return HttpResponseRedirect(reverse('expense_list'))
	else:
		return render(request, 'new_expense.html')



# Upload attachment for business expense
@login_required(login_url='login/')
def upload_business_expense_attachment(request, expense_id):
    # Get expense
    expense = get_object_or_404(Expense, pk=expense_id)

    if request.method == 'POST':
        # Get file from POST data
        myfile = request.FILES['file']

        # Save file to filesystem
        fs = FileSystemStorage()
        fs.save(myfile.name, myfile)

        # Create new ExpenseAttachment record
        e = expense.expenseattachment_set.create(file=myfile, displayname=myfile.name)
        e.save()

		# Redirect to expenses list
        return HttpResponseRedirect(reverse('expense_list'))
    else:
        context = {
            'expense' : expense,
        }
        return render(request, 'upload_attachment.html', context)



# Delete attachment from business expense
@login_required(login_url='login/')
def delete_business_expense_attachment(request, expense_id, expenseattachment_id):
	expense = get_object_or_404(Expense, pk=expense_id)
	expenseattachment = get_object_or_404(ExpenseAttachment, pk=expenseattachment_id)
	try:
		expenseattachment.delete()
		fs = FileSystemStorage()
		fs.delete(expenseattachment)
	except:
		context = {
			'error_message' : "Unable to delete attachment!",
		}
		return render(request, 'expenses.html', context)
	else:
		return HttpResponseRedirect(reverse('expense_list'))



# Delete business expense
@login_required(login_url='login/')
def delete_business_expense(request, expense_id):
	expense = get_object_or_404(Expense, pk=expense_id)
	try:
		expense.delete()
	except (KeyError, Expense.DoesNotExist):
		return render(request, 'expenses.html', {
			'error_message': 'Expense does not exist!',
		})
	else:
		return HttpResponseRedirect(reverse('expense_list'))

invoicemanager/invoicemanager/views/items.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from invoicemanager.models import Customer, Invoice, InvoiceItem, Expense, InvoiceAttachment, ExpenseAttachment



# Add invoiceitem to invoice
@login_required(login_url='login/')
def add_item(request, invoice_id):
	invoice = get_object_or_404(Invoice, pk=invoice_id)
	try:
		i = invoice.invoiceitem_set.create(name=request.POST['name'], description=request.POST['description'], cost=request.POST['cost'], qty=request.POST['qty'])
		i.save()
	except (KeyError, Invoice.DoesNotExist):
		return render(request, 'view_invoice.html', {
			'invoice': invoice,
			'error_message': 'Not all fields were completed.',
		})
	else:
		return HttpResponseRedirect(reverse('invoice', args=(invoice.id,)))



# Delete invoiceitem from invoice
@login_required(login_url='login/')
def delete_item(request, invoiceitem_id, invoice_id):

	item = get_object_or_404(InvoiceItem, pk=invoiceitem_id)
	invoice = get_object_or_404(Invoice, pk=invoice_id)
	try:
		item.delete()
	except (KeyError, InvoiceItem.DoesNotExist):
		return render(request, 'view_invoice.html', {
			'invoice': invoice,
			'error_message': 'Item does not exist.',
		})
	else:
		return HttpResponseRedirect(reverse('invoice', args=(invoice.id,)))

invoicemanager/invoicemanager/views/reports.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
from itertools import chain
import datetime

from invoicemanager.models import Customer, Invoice, InvoiceItem, Expense, InvoiceAttachment, ExpenseAttachment	



# Accounting report
@login_required(login_url='login/')
def accounting(request):
	if request.method == 'POST':
		start = datetime.datetime.strptime(request.POST['start'], "%m/%d/%Y")
		end = datetime.datetime.strptime(request.POST['end'], "%m/%d/%Y")
		
		if start > end:
			context = {
				'error_message' : "Start date must be before end date!",
			}
			return render(request, 'accounting.html', context)
		else:
			paidinvoices = Invoice.objects.filter(date__gt=start).filter(date__lt=end).filter(status = 'Paid')
			allinvoices = Invoice.objects.filter(date__gt=start).filter(date__lt=end)
			expenses = Expense.objects.filter(date__gt=start).filter(date__lt=end)
			
			# Sum of all paid invoices
			invoicetotal = 0
			for i in paidinvoices:
				invoicetotal += i.total_items()
				
			# Add invoice expenses within date range, regardless of invoice status
			for i in allinvoices:
				expenses = list(chain(expenses, Expense.objects.filter(invoice=i)))
			
			# Sum of all expenses
			expensetotal = 0
			for expense in expenses:
				expensetotal += expense.total()
			
			context = {
				'start' : start,
				'end' : end,
				'invoices' : paidinvoices,
				'expenses' : expenses,
				'invoicetotal' : invoicetotal,
				'expensetotal' : expensetotal,
				'nettotal' : invoicetotal - expensetotal,
			}
			return render(request, 'accounting.html', context)
	else:
		return render(request, 'accounting.html')

invoicemanager/invoicemanager/templates/customers.html
{% extends 'base.html' %}

{% block content %}

{% if customers %}

<div class="panel panel-primary">
	<div class="panel-heading">Customer list</div>
	<table class="table table-hover">
		<tr>
			<th>Name</th>
			<th>Invoices</th>
			<th class="text-right">Actions</th>
		</tr>
		{% for customer in customers %}
		<tr>
			<td>{{ customer.name }}</td>
			<td>{{ customer.invoices }}</td>
			<td class="text-right">
				<a href="{% url 'customer' customer.id %}" class="btn btn-xs btn-primary">View</a>
				<a href="mailto:{{ customer.email }}" class="btn btn-xs btn-default">Send Email</a>
				<button type="button" data-toggle="modal" data-target="#confirmdelete" data-object-name="{{ customer.name }}" data-delete-url="{% url 'delete_customer' customer.id %}" class="btn btn-xs btn-danger">Delete</button>
			</td>
		</tr>
		{% endfor %}
	</table>
</div>

<!-- Delete confirmation modal -->
<div class="modal fade" id="confirmdelete" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">Confirm</h4>
			</div>
			<div class="modal-body">

			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">No</button>
				<a href="#" class="btn btn-danger">Yes</a>
			</div>
		</div>
	</div>
</div>

<script>
	$(document).ready(function() {
		$('#confirmdelete').on('show.bs.modal', function(e) {
			var name = $(e.relatedTarget).data('object-name');
			var url = $(e.relatedTarget).data('delete-url');
			$('#confirmdelete .modal-body').html("Are you sure you want to delete " + name + "?<br><i>This will delete all associated invoices, items, expenses, and attachments!</i>");
			$('#confirmdelete .modal-footer a').attr('href', url);
		});
	});
</script>
<!-- END delete confirmation modal -->

{% else %}

<div class="alert alert-warning">No customers!</div>

{% endif %}


{% endblock %}

invoicemanager/invoicemanager/templates/invoice.html
{% extends 'base.html' %}

{% block content %}

{% if error_message %}

<div class="alert alert-danger">{{ error_message }}</div>

{% endif %}

{% if invoice %}
<!-- Display invoice -->

<h2 class="text-center">Invoice {{ invoice.id }}</h2>

<!-- Customer information -->

<form method="POST" action="{% url 'update_invoice' invoice.id %}" name="customer" class="form-horizontal">
	{% csrf_token %}
	<div class="panel panel-primary">
		<div class="panel-heading">Customer</div>
		<div class="panel-body">
			<div class="form-group">
				<label class="col-sm-3 control-label">Customer:</label>
				<div class="col-sm-6">
					<p class="form-control-static"><a href="{% url 'customer' invoice.customer.id %}">{{ invoice.customer }}</a></p>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-3 control-label">Date:</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" name="date" id="invoicedate" value="{{ invoice.date|date:"SHORT_DATE_FORMAT" }}">
				</div>
				<script type="text/javascript">
					$(function () {
						$('#invoicedate').datepicker({
							todayBtn: "linked",
							orientation: "bottom left",
							autoclose: true
						});
					});
					</script>
			</div>
			<div class="form-group">
				<label class="col-sm-3 control-label">Status:</label>
				<div class="col-sm-6">
					<select name="status" class="form-control">
						<option value="Draft" {% if invoice.draft %}selected{% endif %}>Draft</option>
						<option value="Paid" {% if invoice.paid %}selected{% endif %}>Paid</option>
						<option value="Unpaid" {% if invoice.unpaid %}selected{% endif %}>Unpaid</option>
					<select>
				</div>
			</div>
		</div>
		<div class="panel-footer">
			<input type="submit" value="Save" class="btn btn-primary">
			<a href="{% url 'print_invoice' invoice.id %}" target="_new" class="btn btn-default">Printable Invoice</a>
		</div>
	</div>
</form>

<!-- END Customer information -->

<!-- Invoice items -->

<form action="{% url 'add_item' invoice.id %}" method="post" class="form-inline">
	{% csrf_token %}
	<div class="panel panel-primary">
		<div class="panel-heading">Invoice items</div>
		<table class="table table-hover">
			<tr>
				<th>Item</th>
				<th>Description</th>
				<th>Cost</th>
				<th>Qty</th>
				<th>Total</th>
				<th class="text-right">Actions</th>
			</tr>
			{% for item in invoice.invoiceitem_set.all %}
			<tr>
				<td>{{ item.name }}</td>
				<td>{{ item.description }}</td>
				<td>${{ item.cost }}</td>
				<td>{{ item.qty }}</td>
				<td>${{ item.total }}</td>
				<td class="text-right">
					<button type="button" class="btn btn-xs btn-danger" data-toggle="modal" data-target="#confirmdelete" data-object-name="{{ item.description }}" data-delete-url="{% url 'delete_item' invoice.id item.id %}">Delete</button>
				</td>
			</tr>
			{% endfor %}
			<tr>
				<td><input type="text" name="name" class="form-control"></td>
				<td><input type="text" name="description" class="form-control"></td>
				<td>
					<div class="input-group"><span class="input-group-addon">$</span><input type="text" name="cost" class="form-control" placeholder="0.00"/></div>
				</td>
				<td><input type="text" name="qty" class="form-control"></td>
				<td>&nbsp;</td>
				<td class="text-right">
					<input type="submit" class="btn btn-xs btn-primary" value="Add">
				</td>
			</tr>
		</table>
		<div class="panel-footer text-right"><strong>Total: ${{ invoice.total_items }}</strong></div>
	</div>
</form>

<form action="{% url 'add_invoice_expense' invoice.id %}" method="post" class="form-inline">
	{% csrf_token %}
	<div class="panel panel-primary">
		<div class="panel-heading">Invoice expenses</div>
		<table class="table table-hover">
			<tr>
				<th>Description</th>
				<th>Cost</th>
				<th>Qty</th>
				<th>Total</th>
				<th class="text-right">Actions</th>
			</tr>
			{% for expense in invoice.expense_set.all %}
			<tr>
				<td>{{ expense.description }}</td>
				<td>${{ expense.cost }}</td>
				<td>{{ expense.qty }}</td>
				<td>${{ expense.total }}</td>
				<td class="text-right">
					<button type="button" class="btn btn-xs btn-danger" data-toggle="modal" data-target="#confirmdelete" data-object-name="{{ expense.description }}" data-delete-url="{% url 'delete_invoice_expense' invoice.id expense.id %}">Delete</button>
				</td>
			</tr>
			{% endfor %}
			<tr>
				<td><input type="text" name="description" class="form-control"></td>
				<td>
					<div class="input-group"><span class="input-group-addon">$</span><input type="text" name="cost" class="form-control" placeholder="0.00"></div>
				</td>
				<td><input type="text" name="qty" class="form-control"></td>
				<td>&nbsp;</td>
				<td class="text-right">
					<input type="submit" class="btn btn-xs btn-primary" value="Add">
				</td>
			</tr>
		</table>
		<div class="panel-footer text-right"><strong>Total: ${{ invoice.total_expenses }}</strong></div>
	</div>
</form>

<form action="{% url 'upload_invoice_attachment' invoice.id %}" method="POST" enctype="multipart/form-data" class="form-inline">
	{% csrf_token %}
	<div class="panel panel-primary">
		<div class="panel-heading" >Attachments</div>
		<table class="table table-hover">
			<tr>
				<th>File</th>
				<th class="text-right">Actions</th>
			</tr>
			{% for attachment in invoice.invoiceattachment_set.all %}
			<tr>
				<td><a href="{{ attachment.file.url }}">{{ attachment.displayname }}</a></td>
				<td class="text-right">
					<button type="button" data-toggle="modal" data-target="#confirmdelete" data-object-name="{{ attachment.displayname }}" data-delete-url="{% url 'delete_invoice_attachment' invoice.id attachment.id %}" class="btn btn-xs btn-danger">Delete</button>
				</td>
			</tr>
			{% endfor %}
			<tr>
				<td>
					<input type="file" class="file col-sm-6" name="file" id="file" data-show-preview="false">
				</td>
				<td class="text-right">
					<input type="submit" class="btn btn-xs btn-primary" value="Upload">
				</td>
			</tr>
		</table>
	</div>
</form>

<div class="well text-right">Invoice net total: ${{ invoice.total }}</div>


<!-- Delete confirmation modal -->
<div class="modal fade" id="confirmdelete" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">Confirm</h4>
			</div>
			<div class="modal-body">

			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">No</button>
				<a href="#" class="btn btn-danger">Yes</a>
			</div>
		</div>
	</div>
</div>

<script>
	$(document).ready(function() {
		$('#confirmdelete').on('show.bs.modal', function(e) {
			var name = $(e.relatedTarget).data('object-name');
			var url = $(e.relatedTarget).data('delete-url');
			$('#confirmdelete .modal-body').text("Are you sure you want to delete " + name + "?");
			$('#confirmdelete .modal-footer a').attr('href', url);
		});
	});
</script>
<!-- END delete confirmation modal -->



{% if confirm_update %}
<!-- Update success modal -->
<div class="modal fade" id="updateconfirm" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-body">
			<h4>Changes saved!</h4>
        </div>
        <div class="modal-footer">
			<a href="#" data-dismiss="modal" class="btn btn-primary">Ok</a>
        </div>
      </div>
    </div>
</div>

<!-- Trigger success confirmation modal -->
<script>
$(document).ready(function(){
	$("#updateconfirm").modal();
});
</script>
<!-- End success confirmation modal -->
{% endif %}

<!-- End display invoice -->

{% else %}
<!-- Display invoice error -->

<div class="alert alert-warning">Invoice number not found!</div>

<!-- End display invoice error -->
{% endif %}

{% endblock %}

invoicemanager/invoicemanager/templates/login.html
{% extends 'base.html' %}

{% block content %}

<form method="post" action="{% url 'login' %}" class="form-horizontal">
{% csrf_token %}
	<div class="panel panel-primary">
		<div class="panel-heading">Please login</div>
		<div class="panel-body">

			<div class="form-group">
				<label class="col-sm-3 control-label" for="username">Username:</label>
				<div class="col-sm-6"><input type="text" name="username" class="form-control"></div>
			</div>
			<div class="form-group">
				<label class="col-sm-3 control-label" for="password">Password:</label>
				<div class="col-sm-6"><input type="password" name="password" class="form-control"></div>
			</div>

		</div>
		<div class="panel-footer">
			<input type="submit" value="Login" class="btn btn-primary">
		</div>
	</div>
</form>
{% endblock %}

invoicemanager/invoicemanager/templates/upload_attachment.html
{% extends 'base.html' %}

{% block content %}

{% if error_message %}

<div class="alert alert-danger">{{ error_message }}</div>

{% endif %}

{% if expense %}

<form action="{% url 'upload_business_expense_attachment' expense.id %}" method="POST" enctype="multipart/form-data" class="form-inline">
	{% csrf_token %}
	<div class="panel panel-primary">
		<div class="panel-heading" >Attachments</div>
		<div class="panel-body">
			<input type="file" name="file" id="file">
		</div>
		<div class="panel-footer">
			<input type="submit" class="btn btn-xs btn-primary" value="Upload">
		</div>
	</div>
</form>

{% endif %}

{% endblock %}